### ISSUE TITLE
RateController crash since 2.1.1

### ISSUE THREAD

**Issue by mirh** [SK21/AOG#5]
Event log says we have a `System.NullReferenceException in RateController.Program.Main()`
After [checking](https://github.com/SK21/AOG/blob/2.1.3/RC%20Source/RateController/Program.cs), it seems like you crash if `HKCU\SOFTWARE\AgOpenGPS` is not present.

**Comment by SK21** [comment]
Thanks, I will move the Close() statement into the If statement.

**Comment by mirh** [comment]
Thanks, it works now. 
I wish people on the main program repo were this outgoing...

p.s. you probably are better off doing some git revert/rebase magic and delete all the binaries you had slip into the source code. I guess you should add a [.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) file
